### ISSUE TITLE
DbKVS Config Changes

### ISSUE THREAD

**Issue by jboreiko** [palantir/atlasdb#1052]
From @berler 's comments on #504:

The current DBKVS yaml config format also doesn't really make much sense; it combines two completely different things: the Hikari pool config, and the connection config (for individual DB connections). Ideally these would be two separate config blocks to make it clear what is actually being configured.  Fixing this would be an API breaking change.  Also internally the naming on methods and such is inconsistent and confusing (for example there are methods like "getHikariProperties" that are actually not pertaining to Hikari, but simply passed into Hikari and used as Connection parameters).

In my most recent PR I added a connectionParameters block to the config which allows arbitrary JDBC params, the issue is that we still have config outside that block that actually end up as connectionParamters.  The change here would be to remove all parameters that are outside that block and instead rely on setting them correctly in the connectionParameters block.  Remaining parameters that actually pertain to the hikari pool should be put in their own "hikari" block in the config (or this could be named "hikariPoolConfig" etc) rather than being at effectively the top level.

In other words, the current config looks like this:

```yaml
atlasdb:
  keyValueService:
    type: relational
    ddl:
      type: postgres
    connection:
      type: postgres
      host: postgres.palantir.dev
      port: 1000
      dbName: test
      dbLogin: test
      dbPassword: testpassword
      connectionTimeoutSeconds: 5
      socketTimeoutSeconds: 30
      connectionParameters:
        defaultRowFetchSize: 1000
```

My proposed change would be to do this:

```yaml
atlasdb:
  keyValueService:
    type: relational
    hikariPoolConfig:
      # IMPORTANT: see the official hikari documentation for what these mean. These params are completely different
      # from JDBC params. This section can be left out entirely if defaults are acceptable.
      minimumIdle: 8
      maximumPoolSize: 256
      maxLifetime: 1800000
      idleTimeout: 600000
      connectionTimeout: 30000
      leakDetectionThreshold: 0
    databaseConnectionConfig:
      # parameters that pertain to standard DB connections (not the hikari pool)
      # type, host, port, and database are *not* jdbc params but rather get used to construct the jdbc URL
      # (other params could be here, for example oracle also has "sid")
      type: postgres
      host: postgres.palantir.dev
      port: 1000
      database: test
      jdbcParameters:
        # jdbc parameters passed in exactly as is
        user: test
        password: testpassword
        socketTimeout: 100
        defaultRowFetchSize: 1000
```

Other notes about my proposed change: the "ddl" block is not necessary, the ddl type can be inferred from the type on the connection (in the current config it would be broken if you didn't make them match).
