### ISSUE TITLE
We shouldn't allow specifying the database name for DBKVS in the jdbc connection string and the config

### ISSUE THREAD

**Issue by SerialVelocity** [palantir/atlasdb#1083]
Currently we can have a config like:

``` yaml
  keyValueService:
    type: relational
    ddl:
      type: postgres
    connection:
      type: postgres
      host: postgres
      url: jdbc:postgresql://postgres/DB_NAME
      port: 5432
      dbName: DB_NAME
      dbLogin: palantir
      dbPassword: palantir
```

We should either limit `host` to be just a hostname, or restrict it so they cannot specify the db name.
