### ISSUE TITLE
Atlasdb should fail-fast if type is "cassandra" but no has no leader config

### ISSUE THREAD

**Issue by pnepywoda** [palantir/atlasdb#198]
At Magma, atlasdb as configured to use cassandra but the "leader" section of the config wasn't filled out. This resulted in many transient non-deterministic problems like 
```
com.palantir.timestamp.PersistentTimestampService: Throwable while
allocating timestamps.
! com.palantir.timestamp.MultipleRunningTimestampServiceError: Timestamp
limit changed underneath us (limit in memory: 123690317). This may
indicate that another timestamp service is running against this cassandra!
```

I'd be helpful if atlasdb could fail-fast in this case where config was forgotten.

Concretely the atlas yml Magma was using:
```
atlas:
  keyValueService:
    keyspace: atlasdb
    port: "9160"
    replicationFactor: "3"
    servers:
    - lava-sec-cassandra-1.ops.palantir.local
    - lava-seb-cassandra-2.ops.palantir.local
    - lava-sea-cassandra-3.ops.palantir.local
    ssl: "false"
    type: cassandra
```

**Comment by markelliot** [comment]
There's no reasonable detection strategy for this.

**Comment by pnepywoda** [comment]
Could you explain a bit more?

**Comment by markelliot** [comment]
It's perfectly reasonable to run a single instance of a process against a Cassandra cluster. Detecting that the Cassandra cluster is in use by copies of the same process when those processes are not aware of each other is intractable.

**Comment by cshepherd-palantir** [comment]
Can we make leader a mandatory entry in the config when type is set to cassandra?

**Comment by markelliot** [comment]
It doesn't fix the issue you encountered: configure a single leader entry for your Cassandra cluster in two instances, then both will treat themselves as the leader.

**Comment by cshepherd-palantir** [comment]
I agree it doesn't catch that case, but I think the error in this case was a missing leader block altogether. The original config was:
```
atlas:
  keyValueService:
    keyspace: atlasdb
    port: "9160"
    replicationFactor: "3"
    servers:
    - lava-sec-cassandra-1.ops.palantir.local
    - lava-seb-cassandra-2.ops.palantir.local
    - lava-sea-cassandra-3.ops.palantir.local
    ssl: "false"
    type: cassandra
```
and according to @sh4nth "this is a matter of configuring atlas to share the lock & timestamp servers when running in HA.
Your atlas block should look include either a leader block for electing a leader or include lists of lock and timestamp services"

Could we not make it a runtime configuration requirement that if type is cassandra then either leader should be set or lock/timestamp services should be listed. It seems like that would catch a subset of this class of errors, which imo would be a reasonable gain for a small cost.
