### ISSUE TITLE
InMemoryKVS Doesn't Seem To Work with Namespaces

### ISSUE THREAD

**Issue by jeremyk-91** [palantir/atlasdb#2336]
```
server:
  #rootPath: /api/*
  #applicationContextPath: /
  #adminContextPath: /
  applicationConnectors:
    - type: http
      port: 3828
  adminConnectors:
    - type: http
      port: 3829

atlasdb:
  keyValueService:
    type: memory

  namespace: t

  timelock:
    serversList:
      servers:
        - "https://hello:12345"
      sslConfiguration:
        keyStorePath: "keystore.jks"
        trustStorePath: "truststore.jks"
        keyStorePassword: "changeit"
```

Fails with
```
* Failed to parse configuration at: atlasdb; Instantiation of [simple type, class com.palantir.atlasdb.config.ImmutableAtlasDbConfig] value failed: If present, keyspace/dbName/sid config should be the same as the atlas root-level namespace config. (through reference chain: com.palantir.atlasdb.AtlasDbEteConfiguration["atlasdb"])
```
