### ISSUE TITLE
AtlasCli Config Root Should Be A Path

### ISSUE THREAD

**Issue by tpetracca** [palantir/atlasdb#587]
I don't think a single word configuration root that we recursively scan the yaml file for is good enough in case the config root conflicts with something else (or if a file actually has multiple atlas configurations for whatever reason).  It should really be a full qualified path.  So in the following example it would be `root.branch_1.atlasdb` or `/root/branch_1/atlasdb`

```
root:
  branch_0:
    atlasdb:
      this_is_not: an_atlas_config
  branch_1:
    atlasdb:
      keyValueService:
        <rest-of-legit-AtlasDbConfig>
```
